server:
  port: 8090
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    #服务名称
    name: resource-server
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  security:
    oauth2:
      resourceserver:
        jwt:
          # 配置jwk set
          jwk-set-uri: http://localhost:8080/authorization-server/.well-known/jwks.json
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: ${spring.application.name}